Repository cloudfoundry/nfs-volume-release, pull requests merged in 2023-11, with the labels that each got.

#651 Use VMware DNS in CI
  scripts/run-bosh-release-tests-in-docker-env.sh
Labels: unscheduled, ci

#640 Reference harbor to get cf-deployment-concourse-tasks image
  dockerfiles/nfs-integration-tests/Dockerfile
  dockerfiles/nfs-unit-tests/Dockerfile
Labels: unscheduled

#654 Bump OpenSSL to v3.1.4
  config/blobs.yml
Labels: unscheduled, dependencies

#652 [ci] run bosh release tests from the main container
  scripts/run-bosh-release-tests-in-docker-env.sh
Labels: unscheduled

#660 [ci] Fix BOSH release test runner
  scripts/run-bosh-release-tests-in-docker-env.sh
Labels: unscheduled

#657 Bump OpenSSL to v3.1.4
  config/blobs.yml
Labels: unscheduled, dependencies

#661 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, dependencies

#644 prepare openldap autobumps, introduce openssl3
  config/blobs.yml
  jobs/nfstestldapserver/templates/bin/ctl
  jobs/nfstestldapserver/templates/post-start.erb
  packages/openldap/packaging
  packages/openldap/spec
Labels: unscheduled, v5

#643 Enable autobumping openldap
  README.md
  config/blobs.yml
  jobs/nfstestldapserver/spec
  jobs/nfstestldapserver/templates/bin/ctl
  jobs/nfstestldapserver/templates/post-start.erb
  jobs/nfstestldapserver/templates/slapd.ldif.erb
  packages/openldap-2.4.44/packaging
  packages/openldap-2.4.44/spec
  packages/openldap-2.5.13/packaging
  packages/openldap-2.5.13/spec
  packages/openldap/packaging
  packages/openldap/spec
Labels: unscheduled

#662 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
Labels: unscheduled, dependencies

#669 Get images via harbor cache to prevent rate limiting
  dockerfiles/nfs-integration-tests/Dockerfile
Labels: unscheduled

#682 V7 do not use debian packages
  config/blobs.yml
  jobs/nfsv3driver/monit
  jobs/nfsv3driver/spec
  jobs/nfsv3driver/templates/pre-start.erb
  jobs/nfsv3driver/templates/start.sh.erb
  jobs/nfsv3driver/templates/statd.erb
  packages/nfs-debs/packaging
  packages/nfs-debs/spec
  src/bosh_release/bosh_release_test.go
Labels: unscheduled

#685 v5 do not use debian packages
  config/blobs.yml
  jobs/nfsv3driver/monit
  jobs/nfsv3driver/spec
  jobs/nfsv3driver/templates/install.erb
  jobs/nfsv3driver/templates/start.sh.erb
  jobs/nfsv3driver/templates/statd.erb
  packages/nfs-debs/packaging
  packages/nfs-debs/spec
  src/bosh_release/bosh_release_test.go
Labels: unscheduled

#687 change stemcell for tests to use jammy
  src/bosh_release/nfsv3driver-manifest.yml
Labels: unscheduled

#689 split monit jobs for rpc.statd and rpcbind v5
  jobs/nfsv3driver/monit
  jobs/nfsv3driver/spec
  jobs/nfsv3driver/templates/rpcbind.erb
  jobs/nfsv3driver/templates/statd.erb
Labels: unscheduled

#692 Bump OpenSSL to v3.2.0
  config/blobs.yml
Labels: unscheduled, dependencies

#688 split monit jobs for rpc.statd and rpcbind v7
  jobs/nfsv3driver/monit
  jobs/nfsv3driver/spec
  jobs/nfsv3driver/templates/rpcbind.erb
  jobs/nfsv3driver/templates/statd.erb
  src/bosh_release/bosh_release_test.go
Labels: unscheduled

#693 optionally run tests on xenial, default to jammy
  src/bosh_release/bosh_release_suite_test.go
  src/bosh_release/nfsv3driver-manifest.yml
Labels: unscheduled

#694 Bump OpenSSL to v3.2.0
  config/blobs.yml
Labels: unscheduled, dependencies
